FORMAT: 1A

# Misbehaving API as a Service

## Group Behaviours

## General response [/response]

### Timeout request [GET /response/timeout{?t}]
Server will respond in time in seconds

+ Parameters
    + t: 10 (number, optional) - response time in seconds
    
+ Response 200

        Hello world
        
### Redirect hops [GET /response/redirects{?h}]
Server will create redirects hops with 302 status

+ Parameters
    + h: 100 (number, optional) - amount of redirect hops to go through
    
+ Response 302
    + Headers
        
            Location: /

## Response headers [/response/headers]

### Large response header name [GET /response/headers/long-name{?l}]
Response will contain a header with a very long name

+ Parameters
    + l: 5000 (number, optional) - length of the header name

+ Response 200
    + Headers
    
            Fooooooooooooooooooooo: bar

### Large response header value [GET /response/headers/long-value{?l}]
Response will contain a header with a very long value

+ Parameters
    + l: 5000 (number, optional) - length of the header value
    
+ Response 200
    + Headers
    
            Foo: baaaaaaaaaaaaaaaaaaaar

### A lot of headers [GET /response/headers/lot-of-headers{?a}]
Response will contain a lot of headers

+ Parameters
    + a: 1000 (number, optional) - amount of headers returned
    
+ Response 200
    + Headers
    
            Foo: bar
            Bar: baz
            Fizz: Buzz

### Invalid response header [GET /response/headers/invalid]
Response will contain a header that won't be specification compliant

+ Response 200
    + Headers
            
            Wrong header: foo

## Response body [/response/body]

### Large response body [GET /response/body/large{?s}]

+ Parameters
    + s: 10000 (number, optional) - response size in bytes
    
+ Response 200

        Hello world

## Group Utilities

## Chaos [/chaos]

### Random behavior [GET]
Performs one of the behavior, randomly, with random parameters

+ Response 200

        Hello world